name: dart_pact_consumer
description: A consumer library to build and test pact contracts.
version: 0.1.0
# homepage: https://www.example.com
repository: https://github.com/pak3nuh/dart_pact_consumer/tree/main
environment:
  sdk: '>=2.10.4 <2.12.0'

dependencies:
  json_serializable: ">=3.2.0 <4.0.0"
  json_annotation: ^3.0.0
  path: ^1.7.0
  ffi: ^0.1.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.7
  build_runner:
